// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TP2.REST.AccessData;

namespace TP2.REST.AccessData.Migrations
{
    [DbContext(typeof(BibliotecaContext))]
    partial class BibliotecaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TP2.REST.Domain.Entities.Alquiler", b =>
                {
                    b.Property<int>("AlquilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<int>("EstadoID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAlquiler")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaDevolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaReserva")
                        .HasColumnType("datetime2");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("AlquilerId");

                    b.HasIndex("ClienteID");

                    b.HasIndex("EstadoID");

                    b.HasIndex("ISBN");

                    b.ToTable("Alquiler");
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("ClienteId");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            ClienteId = 1,
                            Apellido = "Gargatagli",
                            DNI = "40394722",
                            Email = "ciroshaila@gmail.com",
                            Nombre = "Ciro"
                        });
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.EstadoAlquiler", b =>
                {
                    b.Property<int>("EstadoAlquilerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("EstadoAlquilerId");

                    b.ToTable("EstadoAlquiler");

                    b.HasData(
                        new
                        {
                            EstadoAlquilerId = 1,
                            Descripcion = "Reservado"
                        },
                        new
                        {
                            EstadoAlquilerId = 2,
                            Descripcion = "Alquilado"
                        },
                        new
                        {
                            EstadoAlquilerId = 3,
                            Descripcion = "Cancelado"
                        });
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.Libro", b =>
                {
                    b.Property<string>("ISBN")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Edicion")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Editorial")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("varchar(110)");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(45)");

                    b.HasKey("ISBN");

                    b.ToTable("Libro");

                    b.HasData(
                        new
                        {
                            ISBN = "8478884459",
                            Autor = "J.K. Rowling",
                            Edicion = "1997",
                            Editorial = "Salamandra",
                            Genero = "Fantasía",
                            Imagen = "https://images.cdn2.buscalibre.com/fit-in/360x360/a2/9e/a29ebbd39810f964999f2a9f5f773af8.jpg",
                            Sinopsis = "El día de su cumpleaños, Harry Potter descubre que es hijo de dos conocidos hechiceros, de los que ha heredado poderes mágicos. Debe asistir a una famosa escuela de magia y hechicería, donde entabla una amistad con dos jóvenes que se convertirán en sus compañeros de aventura. Durante su primer año en Hogwarts, descubre que un malévolo y poderoso mago llamado Voldemort está en busca de una piedra filosofal que alarga la vida de quien la posee.",
                            Stock = 10,
                            Titulo = "Harry Potter y la piedra filosofal"
                        },
                        new
                        {
                            ISBN = "6071121639",
                            Autor = "Stephen Chbosky",
                            Edicion = "2013",
                            Editorial = "Alfaguara",
                            Genero = "Novela",
                            Imagen = "https://images-na.ssl-images-amazon.com/images/I/514XOeteoRL._SX319_BO1,204,203,200_.jpg",
                            Sinopsis = "La novela trata sobre un año en la vida de Charlie, desde sus 15 hasta sus 16 años. El joven, retraido y antisocial, ve cambiar su vida cuando conoce a Sam y Patrick, que van a ser muy importantes en su adaptación al mundo de la High School (Escuela Secundaria). Esta escrita en primera persona, a modo de diario.",
                            Stock = 7,
                            Titulo = "Las ventajas de ser invisible"
                        },
                        new
                        {
                            ISBN = "9789876295116",
                            Autor = "Eduardo Galeano",
                            Edicion = "2014",
                            Editorial = "SIGLO XXI EDITORES",
                            Genero = "Literatura Latinoamericana",
                            Imagen = "https://contentv2.tap-commerce.com/cover/large/9789876295116_1.jpg?id_com=1113",
                            Sinopsis = "Las venas abiertas de América Latina, es un ensayo periodístico del escritor uruguayo Eduardo Galeano, contiene crónicas y narraciones que dan pruebas del constante saqueo de recursos naturales que sufrió el continente latinoamericano a lo largo de su historia a manos de naciones colonialistas, del siglo XV al siglo XIX, e imperialistas, del siglo XX en adelante.",
                            Stock = 9,
                            Titulo = "Las Venas Abiertas De America Latina"
                        },
                        new
                        {
                            ISBN = "9788416709823",
                            Autor = "Joe Padilla",
                            Edicion = "2017",
                            Editorial = "RESERVOIR BOOKS",
                            Genero = "Biografía",
                            Imagen = "https://www.isadoralibros.com.uy/sitio/repo/img/9788417125011.jpg",
                            Sinopsis = "Los Ramones explicados a tus hijos. La increíble historia de cuatro amigos que se convirtieron en leyendas del punk rock.Si hay una historia universal de superación esa es la de los Ramones.Y sirve y gusta a todo el mundo.Cuatro inadaptados de Queens,con serios problemas cognitivos,mentales y sociales,lograron el éxito sin saber apenas tocar un instrumento. ¿Su secreto ? El amor por la música y la cultura de serie B",
                            Stock = 15,
                            Titulo = "Ramones"
                        },
                        new
                        {
                            ISBN = "9789872813635",
                            Autor = "Sebastián Duarte",
                            Edicion = "2016",
                            Editorial = "Sebastián Duarte, Sr",
                            Genero = "Biografía",
                            Imagen = "https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcTuZGW7GD3BU0e-JZs2CocWnq28bBt3qS8Rtw&usqp=CAU",
                            Sinopsis = "Biografía documentada sobre el emblemático cantante de punk rock y su paso por Flema.",
                            Stock = 10,
                            Titulo = "Ricky de Flema, El último Punk"
                        },
                        new
                        {
                            ISBN = "9789874109019",
                            Autor = "Roberto Arlt",
                            Edicion = "2016",
                            Editorial = "EDITORIAL BARENHAUS",
                            Genero = "Novela",
                            Imagen = "https://image.isu.pub/181210203225-bdf0823d1bf285c49563674ba22812f3/jpg/page_1.jpg",
                            Sinopsis = "Silvio Astier forma el Club de los Caballeros de Media Noche con los que realiza pequeños hurtos para escapar de su entorno social. ... Silvio Astier, el protagonista de esta novela, es inteligente, de opiniones agudas y culto, pero vive en un entorno social pobre y limitado.",
                            Stock = 6,
                            Titulo = "El Juguete Rabioso"
                        },
                        new
                        {
                            ISBN = "9788491053538",
                            Autor = "Piotr Kropotkin",
                            Edicion = "2017",
                            Editorial = "PENGUIN CLASICOS",
                            Genero = "Novela",
                            Imagen = "https://images-na.ssl-images-amazon.com/images/I/31XJ19CQG1L._SX311_BO1,204,203,200_.jpg",
                            Sinopsis = "Este aristócrata de cuna perseguido por el régimen zarista ofrece un retrato terrible y desolador de los años convulsos previos a las revoluciones de 1905 y 1917, en los que la vida en el palacio de Invierno contrastaba con la situación atroz de los campesinos.",
                            Stock = 13,
                            Titulo = "La conquista del pan"
                        },
                        new
                        {
                            ISBN = "9788491053543",
                            Autor = "Jorge Luis Borges",
                            Edicion = "2018",
                            Editorial = "Debolsillo",
                            Genero = "Literatura Latinoamericana",
                            Imagen = "https://images.cdn1.buscalibre.com/fit-in/360x360/fd/af/fdafb136b6266281c67c860626a8490d.jpg",
                            Sinopsis = "El Aleph es un cuento del escritor argentino Jorge Luis Borges publicado en la revista Sur en 1945 y en el libro homónimo por la editorial Emecé de Buenos Aires en 1949 Argentina. El original se encuentra en la Biblioteca Nacional de España, que lo adquirió por subasta en 1985.",
                            Stock = 6,
                            Titulo = "El Aleph"
                        },
                        new
                        {
                            ISBN = "9732401053543",
                            Autor = "J. R. R. Tolkien",
                            Edicion = "2019",
                            Editorial = "Minotauro",
                            Genero = "Novela",
                            Imagen = "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9788/4450/9788445007709.jpg",
                            Sinopsis = "En la adormecida e idílica Comarca, un joven hobbit recibe un encargo: custodiar el Anillo Único y emprender el viaje para su destrucción en las Grietas del Destino. Consciente de la importancia de su misión, Frodo abandona la Comarca e inicia el camino hacia Mordor con la compañía inesperada de Sam, Pippin y Merry. Pero sólo con la ayuda de Aragorn conseguirán vencer a los Jinetes Negros y alcanzar el refugio de la Casa de Elrond en Rivendel.",
                            Stock = 13,
                            Titulo = "El señor de los anillos"
                        },
                        new
                        {
                            ISBN = "9732401053555",
                            Autor = "Julio Cortazar",
                            Edicion = "2018",
                            Editorial = "Debolsillo",
                            Genero = "Novela",
                            Imagen = "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9788/4663/9788466331906.jpg",
                            Sinopsis = "La obra maestra de Julio Cortázar. Una novela que conmocionó el panorama cultural de su tiempo y marcó un hito insoslayable dentro de la narrativa contemporánea.",
                            Stock = 5,
                            Titulo = "Rayuela"
                        });
                });

            modelBuilder.Entity("TP2.REST.Domain.Entities.Alquiler", b =>
                {
                    b.HasOne("TP2.REST.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.REST.Domain.Entities.EstadoAlquiler", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TP2.REST.Domain.Entities.Libro", "Libro")
                        .WithMany()
                        .HasForeignKey("ISBN")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
